/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Capture {
    id: string;
    name?: string;
    type?: string;
    size: number;
    createdOn: Date;
    uploadedOn: Date;
    hash?: string;
    author?: string;
    notes?: string;
    tags?: Array<string>;
}
