/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Isset2 } from './isset2';


export interface Flow {
    isset: Isset2;
    protocol?: string;
    sourceAddress?: string;
    sourcePort: number;
    destinationAddress?: string;
    destinationPort: number;
    flowId?: string;
    firstSeen: number;
    lastSeen: number;
    packets: number;
    octets: number;
}
