/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Isset } from './isset';


export interface Host {
    isset: Isset;
    address?: string;
    hostname?: string;
    upFlows: number;
    downFlows: number;
    octetsSent: number;
    octetsRecv: number;
    packetsSent: number;
    packetsRecv: number;
}
