/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Tarzan.Nfx.Ingest
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class FrameRefBlock : TBase
  {
    private string _SourceRef;
    private List<FrameRef> _FrameList;

    public string SourceRef
    {
      get
      {
        return _SourceRef;
      }
      set
      {
        __isset.SourceRef = true;
        this._SourceRef = value;
      }
    }

    public List<FrameRef> FrameList
    {
      get
      {
        return _FrameList;
      }
      set
      {
        __isset.FrameList = true;
        this._FrameList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool SourceRef;
      public bool FrameList;
    }

    public FrameRefBlock() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                SourceRef = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  FrameList = new List<FrameRef>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    FrameRef _elem2;
                    _elem2 = new FrameRef();
                    _elem2.Read(iprot);
                    FrameList.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("FrameRefBlock");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (SourceRef != null && __isset.SourceRef) {
          field.Name = "SourceRef";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(SourceRef);
          oprot.WriteFieldEnd();
        }
        if (FrameList != null && __isset.FrameList) {
          field.Name = "FrameList";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, FrameList.Count));
            foreach (FrameRef _iter3 in FrameList)
            {
              _iter3.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("FrameRefBlock(");
      bool __first = true;
      if (SourceRef != null && __isset.SourceRef) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("SourceRef: ");
        __sb.Append(SourceRef);
      }
      if (FrameList != null && __isset.FrameList) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FrameList: ");
        __sb.Append(FrameList);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
