/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Tarzan.Nfx.Ingest
{
  public enum LinkLayerType
  {
    Null = 0,
    Ethernet = 1,
    ExperimentalEthernet3MB = 2,
    AmateurRadioAX25 = 3,
    ProteonProNetTokenRing = 4,
    Chaos = 5,
    Ieee802 = 6,
    ArcNet = 7,
    Slip = 8,
    Ppp = 9,
    Fddi = 10,
    AtmRfc1483 = 11,
    Raw = 12,
    SlipBSD = 15,
    PppBSD = 16,
    AtmClip = 19,
    PppSerial = 50,
    CiscoHDLC = 104,
    Ieee80211 = 105,
    Loop = 108,
    LinuxSLL = 113,
    Ieee80211_Radio = 127,
    PerPacketInformation = 192,
  }
}
