/**
 * TarzanDashboard API
 * TarzanDashboard ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * Contact: rysavy@fit.vutbr.cz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Represents a single flow record.
 */
export interface Capture {
    /**
     * A unique identifier of the capture file.
     */
    id?: number;
    /**
     * The name of the capture file..
     */
    name?: string;
    /**
     * A type of the capture file. It can be pcap, pcapng, etc.
     */
    type?: string;
    /**
     * The total size of the capture file.
     */
    size?: number;
    /**
     * Timestamp when the file was originally created.
     */
    createdOn?: Date;
    /**
     * Timestamp when the file was upload to the system.
     */
    uploadOn?: Date;
    /**
     * Hash value computed by MD5 algorithm.
     */
    hash?: string;
    /**
     * Name of the person who captured the file.
     */
    author?: string;
    /**
     * Arbitrary notes associated with the capture.
     */
    notes?: string;
    /**
     * List of tags that label the capture.
     */
    tags?: Array<string>;
}
