/**
 * TarzanDashboard API
 * TarzanDashboard ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * Contact: rysavy@fit.vutbr.cz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Represents a single flow record.
 */
export interface FlowRecord {
    /**
     * A unique identifier of the flow record.
     */
    id?: number;
    /**
     * Type of transport (or internet) protocol of the flow.
     */
    protocol?: string;
    /**
     * The network source address of the flow.
     */
    sourceAddress?: string;
    /**
     * Source port (if any) of the flow.
     */
    sourcePort?: number;
    /**
     * The network destination address of the flow.
     */
    destinationAddress?: string;
    /**
     * The destination port of the flow.
     */
    destinationPort?: number;
    /**
     * Unix time stamp of the start of flow.
     */
    firstSeen?: number;
    /**
     * The unix time stamp of the end of flow.
     */
    lastSeen?: number;
    /**
     * Number of packets carried by the flow.
     */
    packets?: number;
    /**
     * Total number of octets carried by the flow.
     */
    octets?: number;
}
