/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Tarzan.Nfx.Model
{
  public enum HttpMessageType
  {
    Request = 0,
    Response = 1,
  }
}
