/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Tarzan.Nfx.Model
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class HttpInfo : TBase
  {
    private string _FlowId;
    private string _TransactionId;
    private long _Timestamp;
    private string _Client;
    private string _Server;
    private string _Method;
    private string _Host;
    private string _Uri;
    private string _Referrer;
    private string _Version;
    private string _UserAgent;
    private string _Username;
    private string _Password;
    private string _StatusCode;
    private string _StatusMessage;
    private List<string> _RequestHeaders;
    private List<string> _ResponseHeaders;
    private int _RequestBodyLength;
    private int _ResponseBodyLength;
    private List<byte[]> _RequestBodyChunks;
    private List<byte[]> _ResponseBodyChunks;
    private string _RequestContentType;
    private string _ResponseContentType;

    public string FlowId
    {
      get
      {
        return _FlowId;
      }
      set
      {
        __isset.FlowId = true;
        this._FlowId = value;
      }
    }

    public string TransactionId
    {
      get
      {
        return _TransactionId;
      }
      set
      {
        __isset.TransactionId = true;
        this._TransactionId = value;
      }
    }

    public long Timestamp
    {
      get
      {
        return _Timestamp;
      }
      set
      {
        __isset.Timestamp = true;
        this._Timestamp = value;
      }
    }

    public string Client
    {
      get
      {
        return _Client;
      }
      set
      {
        __isset.Client = true;
        this._Client = value;
      }
    }

    public string Server
    {
      get
      {
        return _Server;
      }
      set
      {
        __isset.Server = true;
        this._Server = value;
      }
    }

    public string Method
    {
      get
      {
        return _Method;
      }
      set
      {
        __isset.Method = true;
        this._Method = value;
      }
    }

    public string Host
    {
      get
      {
        return _Host;
      }
      set
      {
        __isset.Host = true;
        this._Host = value;
      }
    }

    public string Uri
    {
      get
      {
        return _Uri;
      }
      set
      {
        __isset.Uri = true;
        this._Uri = value;
      }
    }

    public string Referrer
    {
      get
      {
        return _Referrer;
      }
      set
      {
        __isset.Referrer = true;
        this._Referrer = value;
      }
    }

    public string Version
    {
      get
      {
        return _Version;
      }
      set
      {
        __isset.Version = true;
        this._Version = value;
      }
    }

    public string UserAgent
    {
      get
      {
        return _UserAgent;
      }
      set
      {
        __isset.UserAgent = true;
        this._UserAgent = value;
      }
    }

    public string Username
    {
      get
      {
        return _Username;
      }
      set
      {
        __isset.Username = true;
        this._Username = value;
      }
    }

    public string Password
    {
      get
      {
        return _Password;
      }
      set
      {
        __isset.Password = true;
        this._Password = value;
      }
    }

    public string StatusCode
    {
      get
      {
        return _StatusCode;
      }
      set
      {
        __isset.StatusCode = true;
        this._StatusCode = value;
      }
    }

    public string StatusMessage
    {
      get
      {
        return _StatusMessage;
      }
      set
      {
        __isset.StatusMessage = true;
        this._StatusMessage = value;
      }
    }

    public List<string> RequestHeaders
    {
      get
      {
        return _RequestHeaders;
      }
      set
      {
        __isset.RequestHeaders = true;
        this._RequestHeaders = value;
      }
    }

    public List<string> ResponseHeaders
    {
      get
      {
        return _ResponseHeaders;
      }
      set
      {
        __isset.ResponseHeaders = true;
        this._ResponseHeaders = value;
      }
    }

    public int RequestBodyLength
    {
      get
      {
        return _RequestBodyLength;
      }
      set
      {
        __isset.RequestBodyLength = true;
        this._RequestBodyLength = value;
      }
    }

    public int ResponseBodyLength
    {
      get
      {
        return _ResponseBodyLength;
      }
      set
      {
        __isset.ResponseBodyLength = true;
        this._ResponseBodyLength = value;
      }
    }

    public List<byte[]> RequestBodyChunks
    {
      get
      {
        return _RequestBodyChunks;
      }
      set
      {
        __isset.RequestBodyChunks = true;
        this._RequestBodyChunks = value;
      }
    }

    public List<byte[]> ResponseBodyChunks
    {
      get
      {
        return _ResponseBodyChunks;
      }
      set
      {
        __isset.ResponseBodyChunks = true;
        this._ResponseBodyChunks = value;
      }
    }

    public string RequestContentType
    {
      get
      {
        return _RequestContentType;
      }
      set
      {
        __isset.RequestContentType = true;
        this._RequestContentType = value;
      }
    }

    public string ResponseContentType
    {
      get
      {
        return _ResponseContentType;
      }
      set
      {
        __isset.ResponseContentType = true;
        this._ResponseContentType = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool FlowId;
      public bool TransactionId;
      public bool Timestamp;
      public bool Client;
      public bool Server;
      public bool Method;
      public bool Host;
      public bool Uri;
      public bool Referrer;
      public bool Version;
      public bool UserAgent;
      public bool Username;
      public bool Password;
      public bool StatusCode;
      public bool StatusMessage;
      public bool RequestHeaders;
      public bool ResponseHeaders;
      public bool RequestBodyLength;
      public bool ResponseBodyLength;
      public bool RequestBodyChunks;
      public bool ResponseBodyChunks;
      public bool RequestContentType;
      public bool ResponseContentType;
    }

    public HttpInfo() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                FlowId = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                TransactionId = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I64) {
                Timestamp = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.String) {
                Client = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.String) {
                Server = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 11:
              if (field.Type == TType.String) {
                Method = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 12:
              if (field.Type == TType.String) {
                Host = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 13:
              if (field.Type == TType.String) {
                Uri = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 14:
              if (field.Type == TType.String) {
                Referrer = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 15:
              if (field.Type == TType.String) {
                Version = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 16:
              if (field.Type == TType.String) {
                UserAgent = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 17:
              if (field.Type == TType.String) {
                Username = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 18:
              if (field.Type == TType.String) {
                Password = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 21:
              if (field.Type == TType.String) {
                StatusCode = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 22:
              if (field.Type == TType.String) {
                StatusMessage = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 31:
              if (field.Type == TType.List) {
                {
                  RequestHeaders = new List<string>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    string _elem2;
                    _elem2 = iprot.ReadString();
                    RequestHeaders.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 32:
              if (field.Type == TType.List) {
                {
                  ResponseHeaders = new List<string>();
                  TList _list3 = iprot.ReadListBegin();
                  for( int _i4 = 0; _i4 < _list3.Count; ++_i4)
                  {
                    string _elem5;
                    _elem5 = iprot.ReadString();
                    ResponseHeaders.Add(_elem5);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 33:
              if (field.Type == TType.I32) {
                RequestBodyLength = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 34:
              if (field.Type == TType.I32) {
                ResponseBodyLength = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 35:
              if (field.Type == TType.List) {
                {
                  RequestBodyChunks = new List<byte[]>();
                  TList _list6 = iprot.ReadListBegin();
                  for( int _i7 = 0; _i7 < _list6.Count; ++_i7)
                  {
                    byte[] _elem8;
                    _elem8 = iprot.ReadBinary();
                    RequestBodyChunks.Add(_elem8);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 36:
              if (field.Type == TType.List) {
                {
                  ResponseBodyChunks = new List<byte[]>();
                  TList _list9 = iprot.ReadListBegin();
                  for( int _i10 = 0; _i10 < _list9.Count; ++_i10)
                  {
                    byte[] _elem11;
                    _elem11 = iprot.ReadBinary();
                    ResponseBodyChunks.Add(_elem11);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 37:
              if (field.Type == TType.String) {
                RequestContentType = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 38:
              if (field.Type == TType.String) {
                ResponseContentType = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("HttpInfo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (FlowId != null && __isset.FlowId) {
          field.Name = "FlowId";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(FlowId);
          oprot.WriteFieldEnd();
        }
        if (TransactionId != null && __isset.TransactionId) {
          field.Name = "TransactionId";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(TransactionId);
          oprot.WriteFieldEnd();
        }
        if (__isset.Timestamp) {
          field.Name = "Timestamp";
          field.Type = TType.I64;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(Timestamp);
          oprot.WriteFieldEnd();
        }
        if (Client != null && __isset.Client) {
          field.Name = "Client";
          field.Type = TType.String;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Client);
          oprot.WriteFieldEnd();
        }
        if (Server != null && __isset.Server) {
          field.Name = "Server";
          field.Type = TType.String;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Server);
          oprot.WriteFieldEnd();
        }
        if (Method != null && __isset.Method) {
          field.Name = "Method";
          field.Type = TType.String;
          field.ID = 11;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Method);
          oprot.WriteFieldEnd();
        }
        if (Host != null && __isset.Host) {
          field.Name = "Host";
          field.Type = TType.String;
          field.ID = 12;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Host);
          oprot.WriteFieldEnd();
        }
        if (Uri != null && __isset.Uri) {
          field.Name = "Uri";
          field.Type = TType.String;
          field.ID = 13;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Uri);
          oprot.WriteFieldEnd();
        }
        if (Referrer != null && __isset.Referrer) {
          field.Name = "Referrer";
          field.Type = TType.String;
          field.ID = 14;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Referrer);
          oprot.WriteFieldEnd();
        }
        if (Version != null && __isset.Version) {
          field.Name = "Version";
          field.Type = TType.String;
          field.ID = 15;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Version);
          oprot.WriteFieldEnd();
        }
        if (UserAgent != null && __isset.UserAgent) {
          field.Name = "UserAgent";
          field.Type = TType.String;
          field.ID = 16;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(UserAgent);
          oprot.WriteFieldEnd();
        }
        if (Username != null && __isset.Username) {
          field.Name = "Username";
          field.Type = TType.String;
          field.ID = 17;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Username);
          oprot.WriteFieldEnd();
        }
        if (Password != null && __isset.Password) {
          field.Name = "Password";
          field.Type = TType.String;
          field.ID = 18;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Password);
          oprot.WriteFieldEnd();
        }
        if (StatusCode != null && __isset.StatusCode) {
          field.Name = "StatusCode";
          field.Type = TType.String;
          field.ID = 21;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(StatusCode);
          oprot.WriteFieldEnd();
        }
        if (StatusMessage != null && __isset.StatusMessage) {
          field.Name = "StatusMessage";
          field.Type = TType.String;
          field.ID = 22;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(StatusMessage);
          oprot.WriteFieldEnd();
        }
        if (RequestHeaders != null && __isset.RequestHeaders) {
          field.Name = "RequestHeaders";
          field.Type = TType.List;
          field.ID = 31;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, RequestHeaders.Count));
            foreach (string _iter12 in RequestHeaders)
            {
              oprot.WriteString(_iter12);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (ResponseHeaders != null && __isset.ResponseHeaders) {
          field.Name = "ResponseHeaders";
          field.Type = TType.List;
          field.ID = 32;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, ResponseHeaders.Count));
            foreach (string _iter13 in ResponseHeaders)
            {
              oprot.WriteString(_iter13);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.RequestBodyLength) {
          field.Name = "RequestBodyLength";
          field.Type = TType.I32;
          field.ID = 33;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(RequestBodyLength);
          oprot.WriteFieldEnd();
        }
        if (__isset.ResponseBodyLength) {
          field.Name = "ResponseBodyLength";
          field.Type = TType.I32;
          field.ID = 34;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ResponseBodyLength);
          oprot.WriteFieldEnd();
        }
        if (RequestBodyChunks != null && __isset.RequestBodyChunks) {
          field.Name = "RequestBodyChunks";
          field.Type = TType.List;
          field.ID = 35;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, RequestBodyChunks.Count));
            foreach (byte[] _iter14 in RequestBodyChunks)
            {
              oprot.WriteBinary(_iter14);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (ResponseBodyChunks != null && __isset.ResponseBodyChunks) {
          field.Name = "ResponseBodyChunks";
          field.Type = TType.List;
          field.ID = 36;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, ResponseBodyChunks.Count));
            foreach (byte[] _iter15 in ResponseBodyChunks)
            {
              oprot.WriteBinary(_iter15);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (RequestContentType != null && __isset.RequestContentType) {
          field.Name = "RequestContentType";
          field.Type = TType.String;
          field.ID = 37;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(RequestContentType);
          oprot.WriteFieldEnd();
        }
        if (ResponseContentType != null && __isset.ResponseContentType) {
          field.Name = "ResponseContentType";
          field.Type = TType.String;
          field.ID = 38;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(ResponseContentType);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("HttpInfo(");
      bool __first = true;
      if (FlowId != null && __isset.FlowId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FlowId: ");
        __sb.Append(FlowId);
      }
      if (TransactionId != null && __isset.TransactionId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TransactionId: ");
        __sb.Append(TransactionId);
      }
      if (__isset.Timestamp) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Timestamp: ");
        __sb.Append(Timestamp);
      }
      if (Client != null && __isset.Client) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Client: ");
        __sb.Append(Client);
      }
      if (Server != null && __isset.Server) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Server: ");
        __sb.Append(Server);
      }
      if (Method != null && __isset.Method) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Method: ");
        __sb.Append(Method);
      }
      if (Host != null && __isset.Host) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Host: ");
        __sb.Append(Host);
      }
      if (Uri != null && __isset.Uri) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Uri: ");
        __sb.Append(Uri);
      }
      if (Referrer != null && __isset.Referrer) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Referrer: ");
        __sb.Append(Referrer);
      }
      if (Version != null && __isset.Version) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Version: ");
        __sb.Append(Version);
      }
      if (UserAgent != null && __isset.UserAgent) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UserAgent: ");
        __sb.Append(UserAgent);
      }
      if (Username != null && __isset.Username) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Username: ");
        __sb.Append(Username);
      }
      if (Password != null && __isset.Password) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Password: ");
        __sb.Append(Password);
      }
      if (StatusCode != null && __isset.StatusCode) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("StatusCode: ");
        __sb.Append(StatusCode);
      }
      if (StatusMessage != null && __isset.StatusMessage) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("StatusMessage: ");
        __sb.Append(StatusMessage);
      }
      if (RequestHeaders != null && __isset.RequestHeaders) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RequestHeaders: ");
        __sb.Append(RequestHeaders);
      }
      if (ResponseHeaders != null && __isset.ResponseHeaders) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ResponseHeaders: ");
        __sb.Append(ResponseHeaders);
      }
      if (__isset.RequestBodyLength) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RequestBodyLength: ");
        __sb.Append(RequestBodyLength);
      }
      if (__isset.ResponseBodyLength) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ResponseBodyLength: ");
        __sb.Append(ResponseBodyLength);
      }
      if (RequestBodyChunks != null && __isset.RequestBodyChunks) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RequestBodyChunks: ");
        __sb.Append(RequestBodyChunks);
      }
      if (ResponseBodyChunks != null && __isset.ResponseBodyChunks) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ResponseBodyChunks: ");
        __sb.Append(ResponseBodyChunks);
      }
      if (RequestContentType != null && __isset.RequestContentType) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RequestContentType: ");
        __sb.Append(RequestContentType);
      }
      if (ResponseContentType != null && __isset.ResponseContentType) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ResponseContentType: ");
        __sb.Append(ResponseContentType);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
