// tslint:disable
/**
 * TarzanDashboard API
 * TarzanDashboard ASP.NET Core Web API
 *
 * OpenAPI spec version: v1
 * Contact: rysavy@fit.vutbr.cz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
